# Project: Casino Game
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
RES      = casino_private.res
OBJ      = mainc.o $(RES)
LINKOBJ  = mainc.o $(RES)
LIBS     = -L"V:/Devolopemt/Dev-Cpp/MinGW64/lib" -L"V:/Devolopemt/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"V:/Devolopemt/Dev-Cpp/MinGW64/include" -I"V:/Devolopemt/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"V:/Devolopemt/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"V:/Devolopemt/Dev-Cpp/MinGW64/include" -I"V:/Devolopemt/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"V:/Devolopemt/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"V:/Devolopemt/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = casino.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

mainc.o: mainc.cpp
	$(CPP) -c mainc.cpp -o mainc.o $(CXXFLAGS)

casino_private.res: casino_private.rc 
	$(WINDRES) -i casino_private.rc --input-format=rc -o casino_private.res -O coff 

